barang/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [    
    path('', daftar_barang, name = 'daftar-barang'),
    path('validate', validate, name='validate'),
    path('validate-update', validate_update, name='validate-update'),
    path('add', add_barang, name='add-barang'),
    path('<str:id_barang>/delete_barang', delete_barang, name='delete-barang'),
    path('<str:id_barang>/update_barang', update_barang, name='update-barang'),
    path('<str:id_barang>', detail_barang, name='detail-barang'),
]

basdatz_tk4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('item.urls','item'),namespace='item')),
    path('', include(('user_profile.urls','user_profile'),namespace='user_profile')),
    path('', include(('pesanan.urls', 'pesanan'), namespace='pesanan')),
    path('', include(('level.urls', 'level'), namespace='level')),
    path('', include(('barang.urls', 'barang'), namespace='barang'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

item/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [  
    path(r'item/', item, name = 'item'),
    path(r'item/create/', create_item, name = 'create_item'),
    url(r'^validate_item/$', validate_item, name='validate_item'),
    url(r'^validate_item_update/$', validate_item_update, name='validate_item_update'),
    url(r'/add_item/$', add_item, name='add_item'),
    url(r'^get_item/$', get_item, name='get_item'),
    url(r'^update_item/$', update_item, name='update_item'),
    url(r'^delete_item/$', delete_item, name='delete_item'),
    url(r'^item/$', item, name='item'),
    url(r'^item/update/(?P<nama>[-\w]+)/$', update_item_page, name='update_item_page'),
]

urlpatterns += staticfiles_urlpatterns()

barang/models.py
from django.db import models

# Create your models here.

barang/forms.py
from django import forms
from utils.db_query_utils import do_raw_sql

#Beberapa potongan kode ini saya dapatkan dari Farhan Azmi

class BarangForm(forms.Form):
    error_messages = {
        'required': 'This field is required',
        'invalid': 'is not valid',
    }
    
    id_barang = forms.CharField(
        label='id_barang', max_length=10, required=True,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-id-barang',
                'name': 'id_barang',
            }))
    
    nama_item = forms.ChoiceField(label="Nama Item",
                                  choices=[
                                      (item["nama"], item["nama"])
                                      for item in do_raw_sql("SELECT nama FROM database_item", fetch=True)
                                  ],
                                  required=True,
                                  widget=forms.TextInput(
                                    attrs = {
                                        'class': 'form-input text-white bb-white',
                                        'id': 'form-nama-item',
                                        'name': 'nama_item',

                                    }))

    warna = forms.CharField(
        label='warna', max_length=50,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-warna',
                'name': 'warna',
                'type':'text'
            }))
    
    url_foto = forms.URLField(
        label="URL Foto", required=False,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-url-foto',
                'name': 'url_foto',
            }))

    kondisi = forms.CharField(
        label="Kondisi", required=True,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-kondisi',
                'name': 'kondisi',
                'type':'text'
            }))

    lama_penggunaan = forms.IntegerField(
        label="Lama Penggunaan", min_value=0, required=False, initial=0,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-lama-penggunaan',
                'name': 'lama_penggunaan',
            }))

    owner = forms.ChoiceField(
        label="Pemilik/Penyewa",
                              choices=[
                                  (member["nama_lengkap"], member["nama_lengkap"])
                                  for member in do_raw_sql("SELECT nama_lengkap FROM database_pengguna "
                                                           "WHERE no_ktp IN "
                                                           "(SELECT no_ktp FROM database_anggota)", fetch=True)
                              ],
                              required=True,
                              widget=forms.TextInput(
                                    attrs = {
                                        'class': 'form-input text-white bb-white',
                                        'id': 'form-owner',
                                        'name': 'owner',
                                    }))

    
    royalti_bronze = forms.CharField(
        label='royalti_bronze', max_length=20,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-royalti-bronze',
                'name': 'royalti_bronze',
            }))

    harga_bronze = forms.IntegerField(
        label='harga_bronze',
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-harga-bronze',
                'name': 'harga_bronze',
            }))

    royalti_silver = forms.CharField(
        label='royalti_silver', max_length=20,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-royalti-silver',
                'name': 'royalti_silver',
            }))

    harga_silver = forms.IntegerField(
        label='harga_silver',
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-harga-silver',
                'name': 'harga_silver',
            }))

    royalti_gold = forms.CharField(
        label='royalti_gold', max_length=20,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-royalti-gold',
                'name': 'royalti_gold',
            }))

    harga_gold = forms.IntegerField(
        label='harga_gold',
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-harga-gold',
                'name': 'harga_gold',
            }))

barang/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import BarangForm
from utils.db_query_utils import do_raw_sql
import psycopg2

# Create your views here.
connection = psycopg2.connect(user = "dzrdxkcfdohvet",
                              password = "a730c0cc7464d18b1028d568d301634ec6b5d47bcee25dbe938702ea358619ff",
                              host = "ec2-54-235-193-0.compute-1.amazonaws.com",
                              port = "5432",
                              database = "d241r20m8gcd79")


def detail_barang(request, id_barang):
    if "no_ktp" in request.session.keys():
        with connection.cursor() as cursor:
            barang_object = cursor.execute("SELECT * FROM barang WHERE id_barang='{}'".format(id_barang))
            related_reviews = cursor.execute("SELECT tanggal_review, review FROM barang_dikirim WHERE id_barang='{}'"
                                     .format(id_barang))
        return render(request, 'barang_detail.html', context={"barang": barang_object[0], "reviews": related_reviews})
    else:
        return HttpResponseRedirect(reverse("login"))

def validate(request):
    id_barang = request.GET.get('id_barang', None)
    
    with connection.cursor() as cursor:
        cursor.execute("""SELECT COUNT(1) FROM barang WHERE id_barang = '%s';""" % (id_barang))        
        v_nama = cursor.fetchone()[0] == 0 #nama tidak ada di database barang
    
    data = {
        'is_available': v_nama
    }
    
    return JsonResponse(data)

def validate_update(request):
    old_id_barang = request.GET.get('old_id_barang', None)
    id_barang = request.GET.get('id_barang', None)
    
    if(id_barang != old_id_barang):
        with connection.cursor() as cursor:
            cursor.execute("""SELECT COUNT(1) FROM barang WHERE id_barang = '%s';""" % (id_barang))
            v_nama = cursor.fetchone()[0] == 0 #nama tidak ada di database barang
    else:
        v_nama = True
    
    data = {
        'is_available': v_nama
    }
    
    return JsonResponse(data)

def daftar_barang(request):
    # TODO REMOVE THESE ONCE MERGED TO MASTER
    request.session["no_ktp"] = "ancol"
    request.session["type"] = "admin"
    if "no_ktp" in request.session.keys():
        return render(request, 'barang_list.html')
    else:
        return HttpResponseRedirect(reverse("login"))


def add_barang(request):
    # TODO cek session role user yang login
    if "no_ktp" in request.session.keys() and request.session["type"] == "admin":
        level_barang = do_raw_sql("SELECT nama_level FROM level_keanggotaan", fetch=True)
        if request.method == "POST":
            form = BarangForm(request.POST)

            if(request.method == 'POST'):
                id_barang = request.POST.get('id_barang', False)
                owner_name = request.POST.get('owner', False)
                royalti_bronze = request.POST.get('royalti_bronze', False)
                harga_bronze = request.POST.get('harga_bronze', False)
                royalti_silver = request.POST.get('royalti_silver', False)
                harga_silver = request.POST.get('harga_silver', False)
                royalti_gold = request.POST.get('royalti_gold', False)
                harga_gold = request.POST.get('harga_bronze', False)
                owner_object = do_raw_sql("SELECT no_ktp FROM pengguna WHERE nama_lengkap='{}'".format(owner_name),
                                          fetch=True)

            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO barang VALUES ('{}', '{}', '{}', '{}', '{}', {}, '{}')".format(
                    id_barang, request.POST["nama_item"], request.POST["warna"],
                    request.POST["url_foto"], request.POST["kondisi"], request.POST["lama_penggunaan"],
                    owner_object[0]["no_ktp"])
                    )
                cursor.execute("INSERT INTO info_barang_level VALUES ('{}', 'bronze', {}, {})"
                                   .format(id_barang, harga_bronze, royalti_bronze)
                    )
                cursor.execute("INSERT INTO info_barang_level VALUES ('{}', 'silver', {}, {})"
                                   .format(id_barang, harga_silver, royalti_silver)
                    )
                cursor.execute("INSERT INTO info_barang_level VALUES ('{}', 'gold', {}, {})"
                                   .format(id_barang, harga_gold, royalti_gold)
                    )
                connection.commit()

                return HttpResponseRedirect(reverse('get-daftar'))

        else:
            form = BarangForm()

def update_barang(request, id_barang):
    # TODO cek session role user yang login
    if "no_ktp" in request.session.keys() and request.session["type"] == "admin":
        level_barang = do_raw_sql("SELECT nama_level FROM level_keanggotaan", fetch=True)
        if request.method == "POST":
            form = BarangForm(request.POST)
    
            if(request.method == 'POST'):
                id_barang = request.POST.get('id_barang', False)
                owner_name = request.POST.get('owner', False)
                royalti_bronze = request.POST.get('royalti_bronze', False)
                harga_bronze = request.POST.get('harga_bronze', False)
                royalti_silver = request.POST.get('royalti_silver', False)
                harga_silver = request.POST.get('harga_silver', False)
                royalti_gold = request.POST.get('royalti_gold', False)
                harga_gold = request.POST.get('harga_bronze', False)
                owner_object = do_raw_sql("SELECT no_ktp FROM pengguna WHERE nama_lengkap='{}'".format(owner_name),
                                          fetch=True)
            
            with connection.cursor() as cursor:
                cursor.execute("UPDATE barang SET nama_item='{}', warna='{}', url_foto='{}', kondisi='{}', "
                        "lama_penggunaan='{}', no_ktp_penyewa='{}' WHERE id_barang='{}'".format(
                            form.cleaned_data["nama_item"], form.cleaned_data["warna"], form.cleaned_data["url_foto"],
                            form.cleaned_data["kondisi"], form.cleaned_data["lama_penggunaan"], owner_object[0]["no_ktp"],
                            id_barang)
                    )
                cursor.execute("UPDATE info_barang_level SET porsi_royalti={}, harga_sewa={} "
                                "WHERE id_barang='{}' AND nama_level='bronze'".format(
                                royalti_bronze, harga_bronze, id_barang)
                    )
                cursor.execute("UPDATE info_barang_level SET porsi_royalti={}, harga_sewa={} "
                                "WHERE id_barang='{}' AND nama_level='silver'".format(
                                royalti_silver, harga_silver, id_barang)
                    )
                cursor.execute("UPDATE info_barang_level SET porsi_royalti={}, harga_sewa={} "
                                "WHERE id_barang='{}' AND nama_level='gold'".format(
                                royalti_gold, harga_gold, id_barang)
                    )
                connection.commit()
    
                return HttpResponseRedirect(reverse('get-daftar'))
    
        else:
            form = BarangForm()
    

def delete_barang(request, id_barang):
    if "no_ktp" in request.session.keys() and request.session["type"] == "admin":
        with connection.cursor() as cursor:
            cursor.execute("DELETE from barang WHERE id_barang='{}'".format(id_barang))            
            return HttpResponseRedirect(reverse("list-barang"))
    else:
        return HttpResponseRedirect(reverse("login"))

barang/templates/barang_detail.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
    <section class="page-section">
        <div class="container">
            {% if barang %}
                <h1 class="my-4">Detail Barang
                    <small>{{ barang.nama_item }}</small>
                </h1>

                <div class="row">

                    <div class="col-md-8">
                        <img class="img-fluid" src="{{ barang.url_foto }}" alt="">
                    </div>

                    <div class="col-md-4">
                        <h3 class="my-3">Detail</h3>
                        <ul>
                            <li>Item: {{ barang.nama_item }}</li>
                            <li>Warna: {{ barang.warna }}</li>
                            <li>Kondisi: {{ barang.kondisi }}</li>
                            <li>Lama Penggunaan: {{ barang.lama_penggunaan }} tahun</li>
                        </ul>
                        {% if reviews %}
                            <h3 class="my-3">Review</h3>
                            <ul>
                                {% for item in reviews %}
                                    <li>[{{ item.tanggal_review }}] - {{ item.review }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <h3 class="my-3">No Reviews Yet</h3>
                        {% endif %}
                        <button type="button" class="btn btn-primary">Pesan</button>
                    </div>
                </div>
            {% else %}
                <h1 class="my-4">Barang Tidak Ditemukan!</h1>
            {% endif %}
        </div>
    </section>
{% endblock content %}

barang/templates/barang_list.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

<div class="container col-sm-12 py-5">
    <div id="secret-obj-type" hidden>{{ request.session.usr_type }}</div>
    {% if request.session.usr_type == "admin" %}
    <div class="col-sm-12 pb-5">
        <div class="row">
            <div class="offset-md-3 col-md-6">
                <a href="{% url 'item:create_item' %}" class="custom-btn btn-lg crimson">Create Item</a>
            </div>
        </div>
    </div>
    {% endif %}
    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4>All Items in Database</h4>
                <div class="table-responsive">        
                    <table id="item-table" class="table table-bordred table-striped">    
                        <thead>
                            <th>ID Barang</th>
                            <th>Nama Item</th>
                            <th>Warna</th>
                            <th>URL Foto</th>
                            <th>Kondisi</th>
                            <th>Lama Penggunaan</th>
                            <th>Owner</th>
                            {% if request.session.usr_type == "admin" %}
                            <th class="admin-hide">Update</th>  
                            <th class="admin-hide">Delete</th>
                            {% endif %}
                        </thead>
                        <tbody id="maBody"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        GetItems();
        
    });
    
    function GetItems(){
        $.ajax({
            type: 'GET',
            url: "/get_item/",
            success: function(data){
                var table_data = '<tbody id="maBody">';
                $.each(data, function(key, value){
                    var url = "/item/update/"+value[0]+"/";
                    table_data += '<tr>';
                    table_data += '<td>'+value[0]+'</td>';
                    table_data += '<td><p>'+value[1]+'</p></td>';
                    table_data += '<td>'+value[2]+'</td>';
                    table_data += '<td>'+value[3]+'</td>';
                    table_data += '<td><p>'+value[4]+'</p></td>';
                    if($("#secret-obj-type").text() == "admin"){
                        table_data += '<td><p data-placement="top" data-toggle="tooltip" title="Update">'
                        table_data += '<a href="' + url + '">'
                        table_data += '<button class="btn btn-primary" data-title="Update"></button></a></p></td>'
                        table_data += '<td><p data-placement="top" data-toggle="tooltip" title="Delete">'
                        table_data += '<button class="btn btn-danger tbtn-delete" data-title="Delete" onclick="'+"DeleteItems('"+value[0]+"')"
                        table_data += '"></button></p></td>'
                    }
                })
                $("#maBody").remove();
                $('#item-table').append(table_data+"</tbody>");
            }
        });
    }
    
    function DeleteItems(nama){
        $.ajax({
            url: "/delete_item/",
            data: {
                'nama': nama,
            },
            dataType: 'json',
            success: function(data){
                alert("data successfully deleted from the database")
                GetItems()
            }
        });
    }
</script>
{% endblock %}

barang/templates/barang_tambah.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

<div class="col-sm-12 bg-theme">
    {% if request.session.usr_type == "admin" %}
    <section class="container form-section py-5">
        <div class='text-white'>
            <form class="form" method="post" action="/item:add_item/">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-12 py-3">
                        <h2>Add an Barang</h2>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-12 mb-4">
                        <div class="alert alert-warning" id="alert-container" hidden>
                            <h4>Warning</h4>
                            <p>
                                <li id="alert-list-1" hidden>An barang with this name already exist</li>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">ID Barang</div>
                            {{ form.id_barang }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nama Item</div>
                            {{ form.nama_item }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Warna</div>
                            {{ form.warna }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">URL Foto</div>
                            {{ form.url_foto }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Lama Penggunaan</div>
                            {{ form.lama_penggunaan }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Owner</div>
                            {{ form.owner }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Bronze</div>
                            Persen Royalti :{{ form.royalti_bronze }}  Harga Sewa :{{ form.harga_bronze }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Silver</div>
                            Persen Royalti :{{ form.royalti_silver }}  Harga Sewa :{{ form.harga_silver }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Gold</div>
                            Persen Royalti :{{ form.royalti_gold }}  Harga Sewa :{{ form.harga_gold }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="mx-auto">
                        <button id="btn-form" class="btn btn-danger btn-form" type="button" name="action" disabled>CREATE</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    {% endif %}
</div>

<script>
    $(".form-input").change(function () {
        var nama = $('#form-nama').val();
    
        $.ajax({
            url: '/validate_item/',
            data: {
                'nama': nama,
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_available) {
                    $('#alert-list-1').prop('hidden', true);
                    $('#alert-container').prop('hidden', true);
                    $('#btn-form').prop('disabled', false);
                } else {
                    $('#alert-list-1').prop('hidden', false);
                    $('#alert-container').prop('hidden', false);
                    $('#btn-form').prop('disabled', true);
                }
            }
        });
    });
    
    $("#btn-form").click(function(e){
        e.preventDefault;
        var id_barang = $('#form-id-barang').val();
        var nama_item = $('#form-nama-item').val();
        var warna = $('#form-warna').val();
        var url_foto = $('#form-url-foto').val();
        var kondisi = $('#form-kondisi').val();
        var lama_penggunaan = $('#form-lama-penggunaan').val();
        var owner = $('#form-owner').val();
        var royalti_bronze = $('#form-royalti-bronze').val();
        var harga_bronze = $('#form-harga-bronze').val();
        var royalti_silver = $('#form-royalti-silver').val();
        var harga_silver = $('#form-harga-silver').val();
        var royalti_gold = $('#form-royalti-gold').val();
        var harga_gold = $('#form-harga-gold').val();
        
        $.ajax({
            url: '/barang/add/',
            type: 'POST',
            data: {
                'id_barang': id_barang,
                'nama_item': nama_item,
                'warna': warna,
                'url_foto': url_foto,
                'kondisi': kondisi,
                'lama_penggunaan': lama_penggunaan,
                'owner': owner,
                'royalti_bronze': royalti_bronze,
                'harga_bronze': harga_bronze,
                'royalti_silver': royalti_silver,
                'harga_silver': harga_silver,
                'royalti_gold': royalti_gold,
                'harga_gold': harga_gold,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function (data) {
                alert("success");
                window.location.href = '/barang/';
            }
        })
    });    
</script>
{% endblock %}