basdatz_tk4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('item.urls','item'),namespace='item')),
    path('', include(('user_profile.urls','user_profile'),namespace='user_profile')),
    path('', include(('pesanan.urls', 'pesanan'), namespace='pesanan')),
    path('', include(('level.urls', 'level'), namespace='level')),
    path('', include(('barang.urls', 'barang'), namespace='barang'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

item/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [  
    path(r'item/', item, name = 'item'),
    path(r'item/create/', create_item, name = 'create_item'),
    url(r'^validate_item/$', validate_item, name='validate_item'),
    url(r'^validate_item_update/$', validate_item_update, name='validate_item_update'),
    url(r'/add_item/$', add_item, name='add_item'),
    url(r'^get_item/$', get_item, name='get_item'),
    url(r'^update_item/$', update_item, name='update_item'),
    url(r'^delete_item/$', delete_item, name='delete_item'),
    url(r'^item/$', item, name='item'),
    url(r'^item/update/(?P<nama>[-\w]+)/$', update_item_page, name='update_item_page'),
]

urlpatterns += staticfiles_urlpatterns()

level/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [
    path(r'level/', level, name='level'),
    path(r'level/List', level_list, name='levelList'),
    path(r'level/new', post_level, name='postLevel'),
    path(r'level/update', update_level, name='updateLevel')

]

urlpatterns += staticfiles_urlpatterns()

login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [  
    path(r'logout/', logout, name = 'logout'),
    path(r'login/', login, name = 'login'),
    path(r'login/admin/', admin, name = 'admin'),
    path(r'login/anggota/', anggota, name = 'anggota'),
    url(r'^login/$', login, name='login'),
    url(r'/logged_in/$', logged_in, name='logged_in'),
    url(r'/add_admin/$', add_admin, name='add_admin'),
    url(r'/add_anggota/$', add_anggota, name='add_anggota'),
    url(r'^ajax/validate_form/$', validate_form, name='validate_form'),
    url(r'^ajax/validate_login/$', validate_login, name='validate_login'),
]

urlpatterns += staticfiles_urlpatterns()

pesanan/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [  
    path(r'pesanan/', pesanan, name='pesanan'),
    path(r'pesanan/list', pesanan_list, name='pesananList'),
    path(r'pesanan/new', post_pesanan, name ='postPesanan'),
    path(r'pesanan/update', update_pesanan, name='updatePesanan')
]

urlpatterns += staticfiles_urlpatterns()

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    if(not 'is_login' in request.session):
        request.session['is_login'] = False
        request.session['usr_type'] = 'Guest'
    response = {
        'nbar': 'index'
    }
    return render(request, 'index.html', response)

base/templates/partials/footer.html
<!-- Footer -->
<footer id="footer" class="py-5 bg-theme-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; BASDAT TK4 2019</p>
    </div>
</footer>

base/templates/partials/header.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-theme-dark fixed-top">
    <div class="container py-1">
        <a id="header-title" class="navbar-brand" href="{% url 'base:index' %}">TOYSRENT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'index' %}active{% endif %}" href="{% url 'base:index' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'pesanan' %}active{% endif %}" href="{% url 'pesanan:pesanan' %}">Pesanan</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'level' %}active{% endif %}" href="{% url 'level:level' %}">Level</a>
                </li>
                
                
                {% if request.session.is_login %}
                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'item' %}active{% endif %}" href="{% url 'item:item' %}">Item</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'barang' %}active{% endif %}" href="{% url 'barang:barang' %}">Barang</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'user_profile' %}active{% endif %}" href="{% url 'user_profile:user_profile' %}">User Profile</a>
                </li>
                {% endif %}
                
                <li class="nav-item">
                    {% if request.session.is_login %}
                    <a href="{% url 'login:logout' %}"><button class="btn btn-danger"> Logout </button></a>
                    {% else %}
                    <a href="{% url 'login:login' %}" ><button class="btn btn-success"> Login </button></a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>