basdatz_tk4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from base.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls','base'),namespace='base')),
    path('', include(('login.urls','login'),namespace='login')),
    path('', include(('item.urls','item'),namespace='item')),
    path('', include(('user_profile.urls','user_profile'),namespace='user_profile')),
    path('', include(('pesanan.urls', 'pesanan'), namespace='pesanan')),
    path('', include(('level.urls', 'level'), namespace='level')),
    path('', include(('barang.urls', 'barang'), namespace='barang'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [    
    path(r'index/', index, name = 'index'),
    url(r'^$', index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import *

urlpatterns = [  
    path(r'logout/', logout, name = 'logout'),
    path(r'login/', login, name = 'login'),
    path(r'login/admin/', admin, name = 'admin'),
    path(r'login/anggota/', anggota, name = 'anggota'),
    url(r'^login/$', login, name='login'),
    url(r'/logged_in/$', logged_in, name='logged_in'),
    url(r'/add_admin/$', add_admin, name='add_admin'),
    url(r'/add_anggota/$', add_anggota, name='add_anggota'),
    url(r'^ajax/validate_form/$', validate_form, name='validate_form'),
    url(r'^ajax/validate_login/$', validate_login, name='validate_login'),
]

urlpatterns += staticfiles_urlpatterns()

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms          
        
class AdminForm(forms.Form):
    error_messages = {
        'required': 'This field is required',
        'invalid': 'is not valid',
    }
    
    no_ktp = forms.IntegerField(
        label='no_ktp', required=True,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-no-ktp',
                'name': 'no ktp',
                'type':'text'
            }))
    
    nama_lengkap = forms.CharField(
        label='nama_lengkap', max_length=200,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-nama-lengkap',
                'name': 'nama lengkap',
                'type':'text'
            }))
    
    email = forms.CharField(
        label='email', max_length=200,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-email',
                'name': 'email',
                'type':'text'
            }))
    
    tanggal_lahir = forms.DateField(
        label='tanggal_lahir',
        widget = forms.DateInput(
            attrs= {
                'class': 'form-input text-white bb-white',
                'id': 'form-tanggal-lahir',
                'name': 'tanggal lahir'
            }))
    
    no_telp = forms.CharField(
        label='no_telp', max_length=20,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-no-telp',
                'name': 'nomor telepon',
                'type':'text'
            }))
    

class AnggotaForm(forms.Form):
    error_messages = {
        'required': 'This field is required',
        'invalid': 'is not valid',
    }
    
    no_ktp = forms.IntegerField(
        label='no_ktp', required=True,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-no-ktp',
                'name': 'no ktp',
                'type':'text'
            }))
    
    nama_lengkap = forms.CharField(
        label='nama_lengkap', max_length=200,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-nama-lengkap',
                'name': 'nama lengkap',
                'type':'text'
            }))
    
    email = forms.CharField(
        label='email', max_length=200,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-email',
                'name': 'email',
                'type':'text'
            }))
    
    tanggal_lahir = forms.DateField(
        label='tanggal_lahir',
        widget = forms.DateInput(
            attrs= {
                'class': 'form-input text-white bb-white',
                'id': 'form-tanggal-lahir',
                'name': 'tanggal lahir'
            }))
    
    no_telp = forms.CharField(
        label='no_telp', max_length=20,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-no-telp',
                'name': 'nomor telepon',
                'type':'text'
            }))
    
    alamat = forms.CharField(
        widget = forms.Textarea(
            attrs = {
                'class': 'form-input text-white bb-white',
                'id': 'form-alamat',
                'name': 'alamat',
                'type':'textarea'
            }))

login/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from .forms import AdminForm, AnggotaForm
from validate_email import validate_email
from database.models import Admin, Anggota, Pengguna
import psycopg2

# Create your views here.
connection = psycopg2.connect(user = "dzrdxkcfdohvet",
                              password = "a730c0cc7464d18b1028d568d301634ec6b5d47bcee25dbe938702ea358619ff",
                              host = "ec2-54-235-193-0.compute-1.amazonaws.com",
                              port = "5432",
                              database = "d241r20m8gcd79")

def login(request):
	return render(request, 'login.html')

def logout(request):
    del request.session['no_ktp']
    del request.session['usr_type']
    del request.session['is_login']
    
    return redirect('/login/')

def admin(request):
    return render(request, 'admin.html', {'form': AdminForm()})

def anggota(request):
	return render(request, 'anggota.html',  {'form': AnggotaForm()})

def validate_form(request):
    no_ktp = request.GET.get('no_ktp', None)
    email = request.GET.get('email', None)
    
    if not no_ktp:
        no_ktp = -1
        
    with connection.cursor() as cursor:
        cursor.execute("""SELECT COUNT(1) FROM database_pengguna WHERE no_ktp = '%s';""" % (no_ktp))        
        v_no_ktp = cursor.fetchone()[0] == 0 #no_ktp tidak ada di database pengguna
        
    v_all = v_no_ktp and validate_email(email)
    
    data = {
        'is_available': v_no_ktp,
        'is_email_invalid': email and not validate_email(email),
        'is_submitable': v_all
    }
    
    return JsonResponse(data)

def validate_login(request):
    no_ktp = request.GET.get('no_ktp', None)
    email = request.GET.get('email', None)
    
    if not no_ktp:
        no_ktp = -1
        
    with connection.cursor() as cursor:
        usr_type = ''
        cursor.execute("""SELECT COUNT(1) FROM database_pengguna WHERE no_ktp = '%s';""" % (no_ktp))   
        v_no_ktp = cursor.fetchone()[0] == 1 #no_ktp ada di database pengguna
        if(v_no_ktp):
            cursor.execute("""SELECT COUNT(1) FROM database_admin WHERE no_ktp_id = '%s';""" % (no_ktp))
            usr_type = 'admin' if cursor.fetchone()[0] == 1 else 'anggota' #no_ktp ada di database admin atau anggota?
                
        cursor.execute("""SELECT COUNT(1) FROM database_pengguna WHERE no_ktp = '%s' AND email = '%s';""" % (no_ktp,email))
        v_email = cursor.fetchone()[0] == 1 #no_ktp memiliki email yang benar
            
    v_all = v_no_ktp and v_email
    
    data = {
        'is_available': v_no_ktp,
        'is_email_valid': v_email,
        'is_submitable': v_all,
        'usr_type': usr_type
    }
    
    return JsonResponse(data)

def logged_in(request):    
    no_ktp = request.GET.get('no_ktp', None)
    email = request.GET.get('email', None)
    usr_type = request.GET.get('usr_type', None)
    
    request.session['no_ktp'] = no_ktp
    request.session['usr_type'] = usr_type
    request.session['is_login'] = True
    
    return redirect('/index/')

def add_admin(request):
    form = AdminForm(request.POST or None)
    
    if(request.method == 'POST' and form.is_valid()):
        no_ktp = request.POST.get('no_ktp', False)
        nama_lengkap = request.POST.get('nama_lengkap', False)
        email = request.POST.get('email', False)
        tanggal_lahir = request.POST.get('tanggal_lahir', False)
        no_telp = request.POST.get('no_telp', False)
        
        with connection.cursor() as cursor:
            cursor.execute("""INSERT INTO database_pengguna VALUES ('%s', '%s', '%s', '%s', '%s');""" % (no_ktp,nama_lengkap,email,tanggal_lahir,no_telp))            
            cursor.execute("""INSERT INTO database_admin VALUES ('%s');""" % (no_ktp))
            connection.commit()
        
    return HttpResponseRedirect('/login/')

def add_anggota(request):
    form = AnggotaForm(request.POST or None)
    
    if(request.method == 'POST' and form.is_valid()):
        no_ktp = request.POST.get('no_ktp', False)
        nama_lengkap = request.POST.get('nama_lengkap', False)
        email = request.POST.get('email', False)
        tanggal_lahir = request.POST.get('tanggal_lahir', False)
        no_telp = request.POST.get('no_telp', False)
        alamat = request.POST.get('alamat', False)
        
        with connection.cursor() as cursor:
            cursor.execute("""INSERT INTO database_pengguna VALUES ('%s', '%s', '%s', '%s', '%s');""" % (no_ktp,nama_lengkap,email,tanggal_lahir,no_telp))            
            cursor.execute("""INSERT INTO database_anggota VALUES ('%s', '%s');""" % (no_ktp,alamat))
            connection.commit()
        
    return HttpResponseRedirect('/login/')

login/templates/admin.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

<div class="col-sm-12 bg-theme">
    <section class="container form-section py-4 col-md-8">
        <div class='text-white'>
            <form class="form" method="post" action="/login:add_admin/">
                {% csrf_token %}

                <div class="row">
                    <div class="col-sm-12 py-3">
                        <h2>Register an Account</h2>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-12 mb-4">
                        <div class="alert alert-warning" id="alert-container" hidden>
                            <h4>Warning</h4>
                            <p>
                                <li>Fields need to have value</li>
                                <li id="alert-list-1" hidden>A user with this ktp number already exists</li>
                                <li id="alert-list-2" hidden>Your email input is invalid</li>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nomor KTP</div>
                            {{ form.no_ktp }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nama Lengkap</div>
                            {{ form.nama_lengkap }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Email</div>
                            {{ form.email }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Tanggal Lahir</div>
                            {{ form.tanggal_lahir }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nomor Telepon</div>
                            {{ form.no_telp }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="mx-auto">
                        <button id="btn-form" class="btn btn-danger btn-form" type="button" name="action" disabled>Create Account</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>

<script>
    $(".form-input").change(function () {
        var no_ktp = $('#form-no-ktp').val();
        var email = $('#form-email').val();
    
        $.ajax({
            url: '/ajax/validate_form/',
            data: {
                'no_ktp': no_ktp,
                'email': email,
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_available) {
                    $('#alert-list-1').prop('hidden', true);
                } else {
                    $('#alert-list-1').prop('hidden', false);
                }
                
                if (data.is_email_invalid){
                    $('#alert-list-2').prop('hidden', false);
                } else {
                    $('#alert-list-2').prop('hidden', true);
                }
                
                if(data.is_submitable) {
                    $('#alert-container').prop('hidden', true);
                    $('#btn-form').prop('disabled', false);
                } else {
                    $('#alert-container').prop('hidden', false);
                    $('#btn-form').prop('disabled', true);
                }
            }
        });
    });
    
    $("#btn-form").click(function(e){
        e.preventDefault;
        var no_ktp = $('#form-no-ktp').val();
        var nama_lengkap = $('#form-nama-lengkap').val();
        var email = $('#form-email').val();
        var tanggal_lahir = $('#form-tanggal-lahir').val();
        var no_telp = $('#form-no-telp').val();
        
        $.ajax({
            url: '/login/add_admin/',
            type: 'POST',
            data: {
                'no_ktp': no_ktp,
                'nama_lengkap': nama_lengkap,
                'email': email,
                'tanggal_lahir': tanggal_lahir,
                'no_telp': no_telp,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function (data) {
                alert("success");
                window.location.href = '/login/';
            }
        })
    });    
</script>

{% endblock %} 

login/templates/anggota.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

<div class="col-sm-12 bg-theme">
    <section class="container form-section py-4 col-md-8">
        <div class='text-white'>
            <form class="form" method="post" action="/login:add_anggota/">
                {% csrf_token %}

                <div class="row">
                    <div class="col-sm-12 py-3">
                        <h2>Register an Account</h2>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-12 mb-4">
                        <div class="alert alert-warning" id="alert-container" hidden>
                            <h4>Warning</h4>
                            <p>
                                <li>Fields need to have value</li>
                                <li id="alert-list-1" hidden>A user with this ktp number already exists</li>
                                <li id="alert-list-2" hidden>Your email input is invalid</li>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nomor KTP</div>
                            {{ form.no_ktp }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nama Lengkap</div>
                            {{ form.nama_lengkap }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Email</div>
                            {{ form.email }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Tanggal Lahir</div>
                            {{ form.tanggal_lahir }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Nomor Telepon</div>
                            {{ form.no_telp }}
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Alamat</div>
                            {{ form.alamat }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="mx-auto">
                        <button id="btn-form" class="btn btn-danger btn-form" type="button" name="action" disabled>Create Account</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>

<script>
    $(".form-input").change(function () {
        var no_ktp = $('#form-no-ktp').val();
        var email = $('#form-email').val();
    
        $.ajax({
            url: '/ajax/validate_form/',
            data: {
                'no_ktp': no_ktp,
                'email': email,
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_available) {
                    $('#alert-list-1').prop('hidden', true);
                } else {
                    $('#alert-list-1').prop('hidden', false);
                }
                
                if (data.is_email_invalid){
                    $('#alert-list-2').prop('hidden', false);
                } else {
                    $('#alert-list-2').prop('hidden', true);
                }
                
                if(data.is_submitable) {
                    $('#alert-container').prop('hidden', true);
                    $('#btn-form').prop('disabled', false);
                } else {
                    $('#alert-container').prop('hidden', false);
                    $('#btn-form').prop('disabled', true);
                }
            }
        });
    });
    
    $("#btn-form").click(function(e){
        e.preventDefault;
        var no_ktp = $('#form-no-ktp').val();
        var nama_lengkap = $('#form-nama-lengkap').val();
        var email = $('#form-email').val();
        var tanggal_lahir = $('#form-tanggal-lahir').val();
        var no_telp = $('#form-no-telp').val();
        var alamat = $('#form-alamat').val();
        
        $.ajax({
            url: '/login/add_anggota/',
            type: 'POST',
            data: {
                'no_ktp': no_ktp,
                'nama_lengkap': nama_lengkap,
                'email': email,
                'tanggal_lahir': tanggal_lahir,
                'no_telp': no_telp,
                'alamat': alamat,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function (data) {
                alert("success");
                window.location.href = '/login/';
            }
        })
    });    
</script>

{% endblock %} 

login/templates/login.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

<div class="col-sm-12 bg-theme text-white pb-5">
    <section class="container form-section col-md-9">
        <div class='text-white'>
            <form class="form">
                <div class="row">
                    <div class="col-sm-12 pt-5">
                        <h2 id="titleh2">Login to an Account</h2>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-12 mb-4">
                        <div class="alert alert-warning" id="alert-container" hidden>
                            <h4>Warning</h4>
                            <p>
                                <li id="alert-list-1" hidden>Pengguna dengan no ktp tersebut tidak ditemukan</li>
                                <li id="alert-list-2" hidden>Email yang dimasukkan tidak sesuai</li>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">Nomor KTP</div>
                            <input type="text" name="Nomor KTP" class="form-input text-white bb-white" id="form-no-ktp">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">Email</div>
                            <input type="text" name="Email" class="form-input text-white bb-white" id="form-email">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="mx-auto">
                        <button id="btn-form" class="btn btn-danger btn-form" type="button" name="action" disabled>SUBMIT</button>
                    </div>
                </div>
            </form>            
        </div>
    </section>  
    <div class="col-sm-12">
        <div class="mx-auto text-center"><h2 class="py-4"> -- OR -- </h2></div>
    </div>
    
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6">
                <a href="{% url 'login:admin' %}" class="custom-btn btn-lg violet">Create Admin</a>
            </div>
            <div class="col-sm-6">
                <a href="{% url 'login:anggota' %}" class="custom-btn btn-lg orange">Create Anggota</a>    
            </div>
        </div>
    </div>
</div>

<script>
    usr_type = '';
    $(".form-input").change(function () {
        var no_ktp = $('#form-no-ktp').val();
        var email = $('#form-email').val();
    
        $.ajax({
            url: '/ajax/validate_login/',
            data: {
                'no_ktp': no_ktp,
                'email': email,
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_available) {
                    $('#alert-list-1').prop('hidden', true);
                } else {
                    $('#alert-list-1').prop('hidden', false);
                }
                
                if (data.is_email_valid){
                    $('#alert-list-2').prop('hidden', true);
                } else {
                    $('#alert-list-2').prop('hidden', false);
                }
                
                if(data.is_submitable) {
                    $('#alert-container').prop('hidden', true);
                    $('#btn-form').prop('disabled', false);
                } else {
                    $('#alert-container').prop('hidden', false);
                    $('#btn-form').prop('disabled', true);
                }
                usr_type = data.usr_type;
            }
        });
    });
    
    $("#btn-form").click(function(e){
        e.preventDefault;
        var no_ktp = $('#form-no-ktp').val();
        var email = $('#form-email').val();
        
        $.ajax({
            url: '/login/logged_in/',
            type: 'GET',
            data: {
                'no_ktp': no_ktp,
                'email': email,
                'usr_type': usr_type
            },
            success: function (data) {
                window.location.href = '/index/';
            }
        })
    });
</script>
{% endblock %}